[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-state"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dev-dependencies]
tempfile.workspace = true

[dependencies]
ahash.workspace             = true
async-trait.workspace             = true
tokio.workspace             = true
anyhow.workspace            = true
bd-bonjson                  = { path = "../bd-bonjson" }
bd-time                  = { path = "../bd-time" }
bd-client-common            = { path = "../bd-client-common" }
bd-resilient-kv             = { path = "../bd-resilient-kv" }
bd-workspace-hack.workspace = true
itertools.workspace         = true
log.workspace               = true
tempfile.workspace          = true
time.workspace              = true
