[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "stats_collection_profiling"
publish      = false
version      = "1.0.0"

[dependencies]
anyhow.workspace            = true
base64-url.workspace        = true
bd-client-common.path       = "../bd-client-common"
bd-client-stats.path        = "../bd-client-stats"
bd-client-stats-store.path  = "../bd-client-stats-store"
bd-log.path                 = "../bd-log"
bd-log-matcher.path         = "../bd-log-matcher"
bd-log-primitives.path      = "../bd-log-primitives"
bd-logger.path              = "../bd-logger"
bd-proto.path               = "../bd-proto"
bd-runtime.path             = "../bd-runtime"
bd-shutdown.path            = "../bd-shutdown"
bd-state.path               = "../bd-state"
bd-stats-common.path        = "../bd-stats-common"
bd-test-helpers.path        = "../bd-test-helpers"
bd-time.path                = "../bd-time"
bd-workflows.path           = "../bd-workflows"
bd-workspace-hack.workspace = true
log.workspace               = true
protobuf.workspace          = true
rand.workspace              = true
sha2.workspace              = true
tempfile.workspace          = true
time.workspace              = true
tokio.workspace             = true
uuid.workspace              = true
