exclude = ["bazel-*", "target/**", "proto/**", "api/**", "thirdparty/flatbuffers/**", "bd-workspace-hack/Cargo.toml"]

[formatting]
align_comments       = true
align_entries        = true
allowed_blank_lines  = 2
array_auto_collapse  = true
array_auto_expand    = true
array_trailing_comma = true
column_width         = 120
reorder_keys         = true
trailing_newline     = true
