[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-proto-util"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
ahash.workspace             = true
anyhow.workspace            = true
base64ct.workspace          = true
bd-proto.path               = "../bd-proto"
bd-workspace-hack.workspace = true
flatbuffers.workspace       = true
itertools.workspace         = true
ordered-float.workspace     = true
protobuf.workspace          = true
sha2.workspace              = true
time.workspace              = true

[dev-dependencies]
bd-macros = { path = "../bd-macros" }

[build-dependencies]
cc.workspace = true

[features]
buffer-log-validate = []
