[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "bd-stats-common"
publish      = false
version      = "1.0.0"

[lib]
doctest = false

[dependencies]
anyhow.workspace            = true
bd-macros.path              = "../bd-macros"
bd-proto-util.path          = "../bd-proto-util"
bd-workspace-hack.workspace = true
protobuf.workspace          = true
sketches-rust.workspace     = true
