[package]
edition      = "2024"
license-file = "../LICENSE"
name         = "logger-cli"
publish      = false
version      = "1.0.0"

[dependencies]
anyhow.workspace             = true
axum.workspace               = true
bd-api.path                  = "../bd-api"
bd-client-common.path        = "../bd-client-common"
bd-device.path               = "../bd-device"
bd-hyper-network.path        = "../bd-hyper-network"
bd-key-value.path            = "../bd-key-value"
bd-log.path                  = "../bd-log"
bd-log-primitives.path       = "../bd-log-primitives"
bd-logger.path               = "../bd-logger"
bd-proto.path                = "../bd-proto"
bd-session.path              = "../bd-session"
bd-shutdown.path             = "../bd-shutdown"
bd-test-helpers.path         = "../bd-test-helpers"
bd-workspace-hack.workspace  = true
clap.workspace               = true
futures.workspace            = true
libc.workspace               = true
log.workspace                = true
parking_lot.workspace        = true
reqwest.workspace            = true
rmcp.workspace               = true
serde.workspace              = true
serde_json.workspace         = true
sqlite.workspace             = true
tarpc.workspace              = true
time.workspace               = true
tokio.workspace              = true
tracing.workspace            = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "logger-mcp"
path = "src/bin/mcp.rs"
